SQL DB implementation using postgres and sequelize
sudharshanreddyam/NodeJSApp pull request #6
Opened 2019-08-13 10:38 UTC by sudharshanreddyam

2019-08-13 13:38 UTC, AliakseiBychyk requested changes

2019-08-13 13:38 UTC, AliakseiBychyk commented on index.js
> +import { sequelize } from "./src/config/connect";
Please use single quotes, the best solution is to setup eslint to maintain the style easily.

2019-08-14 13:39 UTC, sudharshanreddyam commented on index.js
> +import { sequelize } from "./src/config/connect";
Add eslint with Airbnb coding style guide. Fixed the above comment. Thanks for the suggestion.

2019-08-14 16:36 UTC, AliakseiBychyk approved these changes

2019-08-19 07:16 UTC, merged